language: node_js
node_js: "10"
sudo: required
script: "./cli/deploy.sh"
env:
  global:
    secure: ERGNzIRoCMTjxITpdL/nvKPAzzI25EEUv4Dx+/K+scCWhxt5wGiT9ooCUI2XPD3m2JYQCNYKsk0uazrVb+pNUNfibL7Bfy0VOJuIeroJyMwFmpez1sxQoqofjJHxcPRI7RORUTGgDhqCuahhEeD+IipqH6t9gHpsQHcW2/7QuvvdHDd75/3VH+md0A7Ms2Ksueb0X1kBiNQHVtLXqZJLse5LyCo4UFxmGrbvB67mdUl9ylX4jRNb203Z8JIVF/fkSQXqnPFYBa+djKzeAbJCJ4+Qx8WwXQfPzrMNO7XnDrRbYF1GgpMZi9f4s5Y5X3a/ZZmxRG7ujOkhnzOLJWnZGnKOl+/Gj+eHMG1+ceb+aclx9sPN1KFtjVkL0DFc1uZTOoFcGr2oZPz/ac1r7hzyKSg7gnCKvS90LSagE2H1fM39RUtAcC3k+MYWDszXenxLkz4x817kiIAwFmJ6n915Fi6NreNyYpNBffmY3k3fh79o88pRBDep3HaLNh3NUwf+t1yACydSce+U49tLK6tCX0bLSqTRJwEnM5eW0nt4wG3u//BYCjjUdntDXc8DCq4AlofPTBSNi7jktebgDRXfrtxQf1+bIUxB7fgsME2eKwO7qdnLn9Qs3qQdRaJyqVGUX589+HMEfaVon3Jl0x53uTIFlhL5XANHzCMJSxl11tU=
